# Generated by Django 3.2 on 2021-05-06 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0003_auto_20210506_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='description',
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='levelupapi.gamer'),
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
