# Generated by Django 3.2 on 2021-05-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0004_EventUpdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='joined',
            field=models.CharField(default='true', max_length=50),
            preserve_default=False,
        ),
    ]
