# Generated by Django 3.2 on 2021-05-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0005_event_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='joined',
            field=models.BooleanField(),
        ),
    ]
